# Generated by Django 5.0a1 on 2023-10-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
