# Generated by Django 5.0a1 on 2023-10-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
