# Generated by Django 5.0a1 on 2023-10-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
